## Numpy Arrays

In [1]:
import numpy as np

In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(5)

array([0.35852141, 0.86938529, 0.89078145, 0.67545914, 0.12472053])

In [11]:
np.random.rand(5,5)

array([[0.52254238, 0.06199564, 0.80123965, 0.7910391 , 0.97399643],
       [0.44665097, 0.01124501, 0.98928899, 0.04444927, 0.38803134],
       [0.3860223 , 0.55158191, 0.43567813, 0.78053856, 0.59940165],
       [0.18428007, 0.77319775, 0.18594005, 0.19325239, 0.3677215 ],
       [0.12221582, 0.56551014, 0.8644745 , 0.04318137, 0.93179574]])

In [12]:
arr = np.arange(25)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
ranarr = np.random.randint(0,50,10)

In [15]:
ranarr

array([35,  4, 41, 23, 37,  7, 34, 27, 49, 34])

In [16]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
ranarr.max()

np.int64(49)

In [18]:
ranarr.min()

np.int64(4)

In [19]:
ranarr.argmax()

np.int64(8)

In [20]:
arr.shape

(25,)

In [21]:
ranarr.shape

(10,)

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr.shape

(25,)

In [24]:
arr.dtype

dtype('int64')

In [25]:
from numpy.random import randint

In [26]:
randint(1,20)

15

### Numpy Indexing and Arrays

In [27]:
arr = np.arange(0,11)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[8]

np.int64(8)

In [30]:
arr[1:5]

array([1, 2, 3, 4])

In [31]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[0,1]

np.int64(10)

In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [42]:
arr_2d = np.append(arr_2d,[50,55,60])

In [43]:
arr_2d

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 50, 55, 60, 50, 55,
       60])

In [45]:
arr_2d.reshape(3,6)

array([[ 5, 10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55, 60],
       [50, 55, 60, 50, 55, 60]])

In [46]:
arr = np.arange(1,11)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
bool_arr = arr > 5

In [50]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr] # only returns elements where the boolean array is true, this is called conditional indexing

array([ 6,  7,  8,  9, 10])

In [52]:
arr_2d = np.arange(50).reshape(5,10)

In [56]:
arr_2d[1:3,3:5] # format is arr_name[rows slice, cols slice]

array([[13, 14],
       [23, 24]])

## Numpy Operations

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [60]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [63]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [64]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [67]:
arr/arr    #in such cases numpy doesnt give errors but gives a warning

/var/folders/wf/jf67cr5j7j9c4q44ztxqgc8r0000gn/T/ipykernel_37063/2317153573.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr    #in such cases numpy doesnt give errors but gives a warning


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [68]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [69]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [70]:
np.max(arr)

np.int64(10)

In [71]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [72]:
np.log(arr)

/var/folders/wf/jf67cr5j7j9c4q44ztxqgc8r0000gn/T/ipykernel_37063/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])